### ISSUE TITLE
hexpansion corrupt EEPROM causes crash

### ISSUE THREAD

**Issue by Robotmad** [emfcamp/badge-2024-software#164]
**Describe the bug**
It is possible to crash the badge by inserting a hexpansion with corrupt files.

Version: v1.8.0 (likely earlier too)

**To Reproduce**
Insert hexpansion with corrupt files.

Traceback (most recent call last):
  File "main.py", line 39, in <module>
  File "system/scheduler/__init__.py", line 243, in run_forever
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in run_until_complete
  File "system/scheduler/__init__.py", line 239, in _main
  File "asyncio/funcs.py", line 1, in gather
  File "asyncio/core.py", line 1, in run_until_complete
  File "system/eventbus.py", line 95, in run
  File "asyncio/funcs.py", line 1, in gather
  File "asyncio/core.py", line 1, in run_until_complete
  File "system/hexpansion/app.py", line 207, in handle_hexpansion_insertion
  File "system/hexpansion/app.py", line 171, in _mount_eeprom
  File "system/hexpansion/app.py", line 101, in _launch_hexpansion_app
ValueError: incompatible .mpy file
MicroPython 5114f2c-dirty on 2024-06-20; Tildagon with ESP32S3

Will submit a PR to add a try/except around the point where the ValueError is generated.

**Comment by npentrel** [comment]
Thanks for the PR, that should fix it in the next release
