### ISSUE TITLE
app store crash due to network

### ISSUE THREAD

**Issue by ChrisDick** [emfcamp/badge-2024-software#99]
```
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3820,len:0x105c
load:0x403c9700,len:0x4
load:0x403c9704,len:0xbd8
load:0x403cc700,len:0x2e38
entry 0x403c989c
Registered async event handler for RequestForegroundPushEvent: _Scheduler - _handle_request_foreground_push
Registered async event handler for RequestForegroundPopEvent: _Scheduler - _handle_request_foreground_pop
Registered async event handler for RequestStartAppEvent: _Scheduler - _handle_start_app
Registered async event handler for RequestStopAppEvent: _Scheduler - _handle_stop_app
Registered async event handler for HexpansionInsertionEvent: HexpansionManagerApp - handle_hexpansion_insertion
Registered async event handler for HexpansionRemovalEvent: HexpansionManagerApp - handle_hexpansion_removal
Registered event handler for ButtonDownEvent: HexpansionManagerApp - handle_button_down
Registered event handler for ButtonUpEvent: HexpansionManagerApp - handle_button_up
Registered async event handler for PatternEnable: PatternDisplay - _enable
Registered async event handler for PatternDisable: PatternDisplay - _disable
Registered event handler for ButtonDownEvent: Launcher - _handle_buttondown
Registered async event handler for RequestStopAppEvent: Launcher - _handle_stop_app
Registered async event handler for InstallNotificationEvent: Launcher - _handle_refresh_notifications
Registered async event handler for ShowNotificationEvent: NotificationService - _handle_incoming_notification
{}
Creating app firmware_apps.app_store.AppStoreApp...
State Transition: 'init' -> 'wifi_init'
E (8475) wifi:sta is connecting, return error
State Transition: 'wifi_init' -> 'wifi_connecting'
State Transition: 'wifi_connecting' -> 'init'
calling get index
State Transition: 'init' -> 'refreshing_index'
State Transition: 'refreshing_index' -> 'index_received'
Traceback (most recent call last):
  File "system/scheduler/__init__.py", line 181, in app_wrapper
  File "app.py", line 21, in run
  File "firmware_apps/app_store.py", line 251, in update
  File "firmware_apps/app_store.py", line 99, in handle_index
  File "requests/__init__.py", line 33, in json
  File "requests/__init__.py", line 20, in content
OSError: -113
Removing launcher cache for firmware_apps.app_store.AppStoreApp
Stopping app: <RequestStopAppEvent object at 3c2857f0>
Stopping background <AppStoreApp object at 3c29b120>
Stopping  <AppStoreApp object at 3c29b120>
{'firmware_apps.app_store.AppStoreApp': None}
Creating app firmware_apps.app_store.AppStoreApp...
calling get index
State Transition: 'init' -> 'refreshing_index'
State Transition: 'refreshing_index' -> 'index_received'
State Transition: 'index_received' -> 'main_menu'
Registered event handler for ButtonDownEvent: AppStoreApp - _handle_buttondown
State Transition: 'main_menu' -> 'available_menu'
Registered event handler for ButtonDownEvent: AppStoreApp - _handle_buttondown
State Transition: 'available_menu' -> 'available_menu'
State Transition: 'available_menu' -> 'installing_app'
GC
Getting https://codeload.github.com/hughrawlinson/tildagon-battery/legacy.tar.gz/8ff5c2caa15a75b6cbc13117ea2c3ce7b01399c6
Decompressing
Validating
Finding root dir...
prefix: 0, name: pax_global_header
prefix: 1, name: hughrawlinson-tildagon-battery-8ff5c2c/
prefix: 2, name: hughrawlinson-tildagon-battery-8ff5c2c/app.py
prefix: 3, name: hughrawlinson-tildagon-battery-8ff5c2c/tildagon.toml
Found app prefix: hughrawlinson-tildagon-battery-8ff5c2c
Finding app.py...
prefix: 0, name: pax_global_header
prefix: 1, name: hughrawlinson-tildagon-battery-8ff5c2c/
prefix: 2, name: hughrawlinson-tildagon-battery-8ff5c2c/app.py
prefix: 3, name: hughrawlinson-tildagon-battery-8ff5c2c/tildagon.toml
Found app.py at: hughrawlinson-tildagon-battery-8ff5c2c/app.py
Dirname: /apps/hughrawlinson_tildagon_battery/
Creating /apps/hughrawlinson_tildagon_battery/
Filename: /apps/hughrawlinson_tildagon_battery/app.py
Filename: /apps/hughrawlinson_tildagon_battery/tildagon.toml
Json path: /apps/hughrawlinson_tildagon_battery/metadata.json
State Transition: 'installing_app' -> 'main_menu'
Registered event handler for ButtonDownEvent: Launcher - _handle_buttondown
State Transition: 'main_menu' -> 'available_menu'
State Transition: 'available_menu' -> 'available_menu'
```

**Comment by andypiper** [comment]
Possibly no longer valid? Post 1.6.0 and App Store updates?

**Comment by ChrisDick** [comment]
it's no longer raising an exception.
